### ISSUE TITLE
Rename metadata.yaml to metadata.yml

### ISSUE THREAD

**Issue by MohamedEssamAdawy** [threefoldfoundation/blog_example#1]
Blog not working as expected and retrun Kemal has encountered an error. (500) using publishing tools
![image](https://user-images.githubusercontent.com/11272864/105704298-44e9ed80-5f17-11eb-881d-b57d2d3e7f84.png)

After running it locally with publishing tools
![image](https://user-images.githubusercontent.com/11272864/105709060-e7a56a80-5f1d-11eb-8e25-a7946f210382.png)

The error due to missing metadata.yml, The existing file is metadata.yaml

**Comment by abom** [comment]
Rename "metadata.yaml" to "metadata.yml"

**Comment by hossnys** [comment]
fixed here https://github.com/threefoldfoundation/blog_example/commit/35c2b66bc704ce1c7ce5f413447764dfc745586e
